baseURL = "https://www.cloud696.club/"
title = "Cloud 696"
languageCode = "en-gb"
theme = "willock"
paginate = 8

[params]
  description = "chasing the perfect blend"
  copyright = "Copyright © 2022 Cloud 696"
  images = ["images/logo-black-on-white.png"]
  
[permalinks]
 posts = "/:year/:month/:title/"
 mixes = "/:year/:month/:title/"

 [build]
  writeStats = true