baseURL = "http://example.org/"
languageCode = "en-us"
title = "cloud696"
theme = "anelka"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

[params]
  defaultImage = "stock.jpg"
  customCSS = ["css/custom.css"]

[permalinks]
 posts = "/:filename/"