baseURL = "https://cloud696.club/"
title = "cloud696"
languageCode = "en-gb"
theme = "willock"
paginate = 6

[params]
  description = "Making wild combinations of local and global sounds in real time."
  copyright = "Copyright © 2022 cloud696"
  images = ["images/logo-black-on-white.png"]
  
[permalinks]
 posts = "/:year/:month/:title/"
 mixes = "/:year/:month/:title/"

 [build]
  writeStats = true