baseURL = "https://cloud696.club/"
title = "cloud696"
languageCode = "en-gb"
theme = "willock"

[params]
  description = "Global sounds and local patter, broadcasting from South London."
  copyright = "Copyright © 2021 Your Name"
  
[permalinks]
 posts = "/:year/:month/:title/"