baseURL = "https://cloud696.club/"
title = "cloud696"
languageCode = "en-gb"
theme = "willock"

[params]
  description = "Your site description"
  copyright = "Copyright © 2021 Your Name"
  
[permalinks]
 posts = "/:year/:month/:title/"