baseURL = "https://cloud696.club/"
title = "cloud696"
languageCode = "en-gb"
theme = "willock"
paginate = 6

[params]
  description = "Global sounds and local patter out of South London."
  copyright = "Copyright © 2021 cloud696"
  images = ["images/logo-white.png"]
  
[permalinks]
 posts = "/:year/:month/:title/"

 [build]
  writeStats = true