baseURL = "https://www.cloud696.club/"
title = "Cloud 696"
languageCode = "en-gb"
theme = "willock"

[pagination]
  disableAliases = false
  pagerSize = 8

[taxonomies]
  category = 'categories'
  tag = 'tags'
  station = 'station'

[params]
  description = "clanging but charming since 2k21"
  copyright = "Copyright © 2024 Cloud 696"
  images = ["images/logo-black-on-white.png"]
  
[permalinks]
  posts = "/posts/:slug/"
  radio = "/radio/:slug/"

[build]
  writeStats = true

[markup.goldmark.renderer]
  unsafe= true
