baseURL = "https://cloud696.club/"
languageCode = "en-us"
title = "cloud696"
theme = "willock"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

[permalinks]
 posts = "/:filename/"